// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"hmdp/ent/blog"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BlogCreate is the builder for creating a Blog entity.
type BlogCreate struct {
	config
	mutation *BlogMutation
	hooks    []Hook
}

// SetShopId sets the "shopId" field.
func (bc *BlogCreate) SetShopId(i int64) *BlogCreate {
	bc.mutation.SetShopId(i)
	return bc
}

// SetUserId sets the "userId" field.
func (bc *BlogCreate) SetUserId(i int64) *BlogCreate {
	bc.mutation.SetUserId(i)
	return bc
}

// SetTitle sets the "title" field.
func (bc *BlogCreate) SetTitle(s string) *BlogCreate {
	bc.mutation.SetTitle(s)
	return bc
}

// SetImages sets the "images" field.
func (bc *BlogCreate) SetImages(s string) *BlogCreate {
	bc.mutation.SetImages(s)
	return bc
}

// SetContent sets the "content" field.
func (bc *BlogCreate) SetContent(s string) *BlogCreate {
	bc.mutation.SetContent(s)
	return bc
}

// SetLiked sets the "liked" field.
func (bc *BlogCreate) SetLiked(i int) *BlogCreate {
	bc.mutation.SetLiked(i)
	return bc
}

// SetComments sets the "comments" field.
func (bc *BlogCreate) SetComments(i int) *BlogCreate {
	bc.mutation.SetComments(i)
	return bc
}

// SetCreateTime sets the "createTime" field.
func (bc *BlogCreate) SetCreateTime(t time.Time) *BlogCreate {
	bc.mutation.SetCreateTime(t)
	return bc
}

// SetUpdateTime sets the "updateTime" field.
func (bc *BlogCreate) SetUpdateTime(t time.Time) *BlogCreate {
	bc.mutation.SetUpdateTime(t)
	return bc
}

// SetID sets the "id" field.
func (bc *BlogCreate) SetID(i int64) *BlogCreate {
	bc.mutation.SetID(i)
	return bc
}

// Mutation returns the BlogMutation object of the builder.
func (bc *BlogCreate) Mutation() *BlogMutation {
	return bc.mutation
}

// Save creates the Blog in the database.
func (bc *BlogCreate) Save(ctx context.Context) (*Blog, error) {
	return withHooks(ctx, bc.sqlSave, bc.mutation, bc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (bc *BlogCreate) SaveX(ctx context.Context) *Blog {
	v, err := bc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bc *BlogCreate) Exec(ctx context.Context) error {
	_, err := bc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bc *BlogCreate) ExecX(ctx context.Context) {
	if err := bc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bc *BlogCreate) check() error {
	if _, ok := bc.mutation.ShopId(); !ok {
		return &ValidationError{Name: "shopId", err: errors.New(`ent: missing required field "Blog.shopId"`)}
	}
	if _, ok := bc.mutation.UserId(); !ok {
		return &ValidationError{Name: "userId", err: errors.New(`ent: missing required field "Blog.userId"`)}
	}
	if _, ok := bc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Blog.title"`)}
	}
	if _, ok := bc.mutation.Images(); !ok {
		return &ValidationError{Name: "images", err: errors.New(`ent: missing required field "Blog.images"`)}
	}
	if _, ok := bc.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Blog.content"`)}
	}
	if _, ok := bc.mutation.Liked(); !ok {
		return &ValidationError{Name: "liked", err: errors.New(`ent: missing required field "Blog.liked"`)}
	}
	if _, ok := bc.mutation.Comments(); !ok {
		return &ValidationError{Name: "comments", err: errors.New(`ent: missing required field "Blog.comments"`)}
	}
	if _, ok := bc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "createTime", err: errors.New(`ent: missing required field "Blog.createTime"`)}
	}
	if _, ok := bc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "updateTime", err: errors.New(`ent: missing required field "Blog.updateTime"`)}
	}
	if v, ok := bc.mutation.ID(); ok {
		if err := blog.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Blog.id": %w`, err)}
		}
	}
	return nil
}

func (bc *BlogCreate) sqlSave(ctx context.Context) (*Blog, error) {
	if err := bc.check(); err != nil {
		return nil, err
	}
	_node, _spec := bc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	bc.mutation.id = &_node.ID
	bc.mutation.done = true
	return _node, nil
}

func (bc *BlogCreate) createSpec() (*Blog, *sqlgraph.CreateSpec) {
	var (
		_node = &Blog{config: bc.config}
		_spec = sqlgraph.NewCreateSpec(blog.Table, sqlgraph.NewFieldSpec(blog.FieldID, field.TypeInt64))
	)
	if id, ok := bc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := bc.mutation.ShopId(); ok {
		_spec.SetField(blog.FieldShopId, field.TypeInt64, value)
		_node.ShopId = value
	}
	if value, ok := bc.mutation.UserId(); ok {
		_spec.SetField(blog.FieldUserId, field.TypeInt64, value)
		_node.UserId = value
	}
	if value, ok := bc.mutation.Title(); ok {
		_spec.SetField(blog.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := bc.mutation.Images(); ok {
		_spec.SetField(blog.FieldImages, field.TypeString, value)
		_node.Images = value
	}
	if value, ok := bc.mutation.Content(); ok {
		_spec.SetField(blog.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := bc.mutation.Liked(); ok {
		_spec.SetField(blog.FieldLiked, field.TypeInt, value)
		_node.Liked = value
	}
	if value, ok := bc.mutation.Comments(); ok {
		_spec.SetField(blog.FieldComments, field.TypeInt, value)
		_node.Comments = value
	}
	if value, ok := bc.mutation.CreateTime(); ok {
		_spec.SetField(blog.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := bc.mutation.UpdateTime(); ok {
		_spec.SetField(blog.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	return _node, _spec
}

// BlogCreateBulk is the builder for creating many Blog entities in bulk.
type BlogCreateBulk struct {
	config
	builders []*BlogCreate
}

// Save creates the Blog entities in the database.
func (bcb *BlogCreateBulk) Save(ctx context.Context) ([]*Blog, error) {
	specs := make([]*sqlgraph.CreateSpec, len(bcb.builders))
	nodes := make([]*Blog, len(bcb.builders))
	mutators := make([]Mutator, len(bcb.builders))
	for i := range bcb.builders {
		func(i int, root context.Context) {
			builder := bcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BlogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bcb *BlogCreateBulk) SaveX(ctx context.Context) []*Blog {
	v, err := bcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bcb *BlogCreateBulk) Exec(ctx context.Context) error {
	_, err := bcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bcb *BlogCreateBulk) ExecX(ctx context.Context) {
	if err := bcb.Exec(ctx); err != nil {
		panic(err)
	}
}
