// Code generated by ent, DO NOT EDIT.

package ent

import (
	"hmdp/ent/blog"
	"hmdp/ent/schema"
	"hmdp/ent/shop"
	"hmdp/ent/shoptype"
	"hmdp/ent/user"
	"hmdp/ent/voucher"
	"hmdp/ent/voucherorder"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	blogFields := schema.Blog{}.Fields()
	_ = blogFields
	// blogDescID is the schema descriptor for id field.
	blogDescID := blogFields[0].Descriptor()
	// blog.IDValidator is a validator for the "id" field. It is called by the builders before save.
	blog.IDValidator = blogDescID.Validators[0].(func(int64) error)
	shopFields := schema.Shop{}.Fields()
	_ = shopFields
	// shopDescID is the schema descriptor for id field.
	shopDescID := shopFields[0].Descriptor()
	// shop.IDValidator is a validator for the "id" field. It is called by the builders before save.
	shop.IDValidator = shopDescID.Validators[0].(func(int64) error)
	shoptypeFields := schema.ShopType{}.Fields()
	_ = shoptypeFields
	// shoptypeDescID is the schema descriptor for id field.
	shoptypeDescID := shoptypeFields[0].Descriptor()
	// shoptype.IDValidator is a validator for the "id" field. It is called by the builders before save.
	shoptype.IDValidator = shoptypeDescID.Validators[0].(func(int64) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(uint64) error)
	voucherFields := schema.Voucher{}.Fields()
	_ = voucherFields
	// voucherDescCreateTime is the schema descriptor for create_time field.
	voucherDescCreateTime := voucherFields[9].Descriptor()
	// voucher.DefaultCreateTime holds the default value on creation for the create_time field.
	voucher.DefaultCreateTime = voucherDescCreateTime.Default.(time.Time)
	// voucherDescUpdateTime is the schema descriptor for update_time field.
	voucherDescUpdateTime := voucherFields[10].Descriptor()
	// voucher.DefaultUpdateTime holds the default value on creation for the update_time field.
	voucher.DefaultUpdateTime = voucherDescUpdateTime.Default.(time.Time)
	voucherorderFields := schema.VoucherOrder{}.Fields()
	_ = voucherorderFields
	// voucherorderDescCreateTime is the schema descriptor for create_time field.
	voucherorderDescCreateTime := voucherorderFields[8].Descriptor()
	// voucherorder.DefaultCreateTime holds the default value on creation for the create_time field.
	voucherorder.DefaultCreateTime = voucherorderDescCreateTime.Default.(time.Time)
	// voucherorderDescUpdateTime is the schema descriptor for update_time field.
	voucherorderDescUpdateTime := voucherorderFields[9].Descriptor()
	// voucherorder.DefaultUpdateTime holds the default value on creation for the update_time field.
	voucherorder.DefaultUpdateTime = voucherorderDescUpdateTime.Default.(time.Time)
}
