// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"hmdp/ent/predicate"
	"hmdp/ent/seckillvoucher"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SeckillVoucherDelete is the builder for deleting a SeckillVoucher entity.
type SeckillVoucherDelete struct {
	config
	hooks    []Hook
	mutation *SeckillVoucherMutation
}

// Where appends a list predicates to the SeckillVoucherDelete builder.
func (svd *SeckillVoucherDelete) Where(ps ...predicate.SeckillVoucher) *SeckillVoucherDelete {
	svd.mutation.Where(ps...)
	return svd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (svd *SeckillVoucherDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, svd.sqlExec, svd.mutation, svd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (svd *SeckillVoucherDelete) ExecX(ctx context.Context) int {
	n, err := svd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (svd *SeckillVoucherDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(seckillvoucher.Table, sqlgraph.NewFieldSpec(seckillvoucher.FieldID, field.TypeUint64))
	if ps := svd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, svd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	svd.mutation.done = true
	return affected, err
}

// SeckillVoucherDeleteOne is the builder for deleting a single SeckillVoucher entity.
type SeckillVoucherDeleteOne struct {
	svd *SeckillVoucherDelete
}

// Where appends a list predicates to the SeckillVoucherDelete builder.
func (svdo *SeckillVoucherDeleteOne) Where(ps ...predicate.SeckillVoucher) *SeckillVoucherDeleteOne {
	svdo.svd.mutation.Where(ps...)
	return svdo
}

// Exec executes the deletion query.
func (svdo *SeckillVoucherDeleteOne) Exec(ctx context.Context) error {
	n, err := svdo.svd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{seckillvoucher.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (svdo *SeckillVoucherDeleteOne) ExecX(ctx context.Context) {
	if err := svdo.Exec(ctx); err != nil {
		panic(err)
	}
}
