// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"hmdp/ent/predicate"
	"hmdp/ent/seckillvoucher"
	"hmdp/ent/voucher"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SeckillVoucherQuery is the builder for querying SeckillVoucher entities.
type SeckillVoucherQuery struct {
	config
	ctx         *QueryContext
	order       []seckillvoucher.OrderOption
	inters      []Interceptor
	predicates  []predicate.SeckillVoucher
	withGetForm *VoucherQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SeckillVoucherQuery builder.
func (svq *SeckillVoucherQuery) Where(ps ...predicate.SeckillVoucher) *SeckillVoucherQuery {
	svq.predicates = append(svq.predicates, ps...)
	return svq
}

// Limit the number of records to be returned by this query.
func (svq *SeckillVoucherQuery) Limit(limit int) *SeckillVoucherQuery {
	svq.ctx.Limit = &limit
	return svq
}

// Offset to start from.
func (svq *SeckillVoucherQuery) Offset(offset int) *SeckillVoucherQuery {
	svq.ctx.Offset = &offset
	return svq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (svq *SeckillVoucherQuery) Unique(unique bool) *SeckillVoucherQuery {
	svq.ctx.Unique = &unique
	return svq
}

// Order specifies how the records should be ordered.
func (svq *SeckillVoucherQuery) Order(o ...seckillvoucher.OrderOption) *SeckillVoucherQuery {
	svq.order = append(svq.order, o...)
	return svq
}

// QueryGetForm chains the current query on the "getForm" edge.
func (svq *SeckillVoucherQuery) QueryGetForm() *VoucherQuery {
	query := (&VoucherClient{config: svq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := svq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := svq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(seckillvoucher.Table, seckillvoucher.FieldID, selector),
			sqlgraph.To(voucher.Table, voucher.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, seckillvoucher.GetFormTable, seckillvoucher.GetFormColumn),
		)
		fromU = sqlgraph.SetNeighbors(svq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SeckillVoucher entity from the query.
// Returns a *NotFoundError when no SeckillVoucher was found.
func (svq *SeckillVoucherQuery) First(ctx context.Context) (*SeckillVoucher, error) {
	nodes, err := svq.Limit(1).All(setContextOp(ctx, svq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{seckillvoucher.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (svq *SeckillVoucherQuery) FirstX(ctx context.Context) *SeckillVoucher {
	node, err := svq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SeckillVoucher ID from the query.
// Returns a *NotFoundError when no SeckillVoucher ID was found.
func (svq *SeckillVoucherQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = svq.Limit(1).IDs(setContextOp(ctx, svq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{seckillvoucher.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (svq *SeckillVoucherQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := svq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SeckillVoucher entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SeckillVoucher entity is found.
// Returns a *NotFoundError when no SeckillVoucher entities are found.
func (svq *SeckillVoucherQuery) Only(ctx context.Context) (*SeckillVoucher, error) {
	nodes, err := svq.Limit(2).All(setContextOp(ctx, svq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{seckillvoucher.Label}
	default:
		return nil, &NotSingularError{seckillvoucher.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (svq *SeckillVoucherQuery) OnlyX(ctx context.Context) *SeckillVoucher {
	node, err := svq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SeckillVoucher ID in the query.
// Returns a *NotSingularError when more than one SeckillVoucher ID is found.
// Returns a *NotFoundError when no entities are found.
func (svq *SeckillVoucherQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = svq.Limit(2).IDs(setContextOp(ctx, svq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{seckillvoucher.Label}
	default:
		err = &NotSingularError{seckillvoucher.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (svq *SeckillVoucherQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := svq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SeckillVouchers.
func (svq *SeckillVoucherQuery) All(ctx context.Context) ([]*SeckillVoucher, error) {
	ctx = setContextOp(ctx, svq.ctx, "All")
	if err := svq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SeckillVoucher, *SeckillVoucherQuery]()
	return withInterceptors[[]*SeckillVoucher](ctx, svq, qr, svq.inters)
}

// AllX is like All, but panics if an error occurs.
func (svq *SeckillVoucherQuery) AllX(ctx context.Context) []*SeckillVoucher {
	nodes, err := svq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SeckillVoucher IDs.
func (svq *SeckillVoucherQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if svq.ctx.Unique == nil && svq.path != nil {
		svq.Unique(true)
	}
	ctx = setContextOp(ctx, svq.ctx, "IDs")
	if err = svq.Select(seckillvoucher.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (svq *SeckillVoucherQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := svq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (svq *SeckillVoucherQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, svq.ctx, "Count")
	if err := svq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, svq, querierCount[*SeckillVoucherQuery](), svq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (svq *SeckillVoucherQuery) CountX(ctx context.Context) int {
	count, err := svq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (svq *SeckillVoucherQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, svq.ctx, "Exist")
	switch _, err := svq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (svq *SeckillVoucherQuery) ExistX(ctx context.Context) bool {
	exist, err := svq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SeckillVoucherQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (svq *SeckillVoucherQuery) Clone() *SeckillVoucherQuery {
	if svq == nil {
		return nil
	}
	return &SeckillVoucherQuery{
		config:      svq.config,
		ctx:         svq.ctx.Clone(),
		order:       append([]seckillvoucher.OrderOption{}, svq.order...),
		inters:      append([]Interceptor{}, svq.inters...),
		predicates:  append([]predicate.SeckillVoucher{}, svq.predicates...),
		withGetForm: svq.withGetForm.Clone(),
		// clone intermediate query.
		sql:  svq.sql.Clone(),
		path: svq.path,
	}
}

// WithGetForm tells the query-builder to eager-load the nodes that are connected to
// the "getForm" edge. The optional arguments are used to configure the query builder of the edge.
func (svq *SeckillVoucherQuery) WithGetForm(opts ...func(*VoucherQuery)) *SeckillVoucherQuery {
	query := (&VoucherClient{config: svq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	svq.withGetForm = query
	return svq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		VoucherID uint64 `json:"voucher_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SeckillVoucher.Query().
//		GroupBy(seckillvoucher.FieldVoucherID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (svq *SeckillVoucherQuery) GroupBy(field string, fields ...string) *SeckillVoucherGroupBy {
	svq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SeckillVoucherGroupBy{build: svq}
	grbuild.flds = &svq.ctx.Fields
	grbuild.label = seckillvoucher.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		VoucherID uint64 `json:"voucher_id,omitempty"`
//	}
//
//	client.SeckillVoucher.Query().
//		Select(seckillvoucher.FieldVoucherID).
//		Scan(ctx, &v)
func (svq *SeckillVoucherQuery) Select(fields ...string) *SeckillVoucherSelect {
	svq.ctx.Fields = append(svq.ctx.Fields, fields...)
	sbuild := &SeckillVoucherSelect{SeckillVoucherQuery: svq}
	sbuild.label = seckillvoucher.Label
	sbuild.flds, sbuild.scan = &svq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SeckillVoucherSelect configured with the given aggregations.
func (svq *SeckillVoucherQuery) Aggregate(fns ...AggregateFunc) *SeckillVoucherSelect {
	return svq.Select().Aggregate(fns...)
}

func (svq *SeckillVoucherQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range svq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, svq); err != nil {
				return err
			}
		}
	}
	for _, f := range svq.ctx.Fields {
		if !seckillvoucher.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if svq.path != nil {
		prev, err := svq.path(ctx)
		if err != nil {
			return err
		}
		svq.sql = prev
	}
	return nil
}

func (svq *SeckillVoucherQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SeckillVoucher, error) {
	var (
		nodes       = []*SeckillVoucher{}
		_spec       = svq.querySpec()
		loadedTypes = [1]bool{
			svq.withGetForm != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SeckillVoucher).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SeckillVoucher{config: svq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, svq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := svq.withGetForm; query != nil {
		if err := svq.loadGetForm(ctx, query, nodes, nil,
			func(n *SeckillVoucher, e *Voucher) { n.Edges.GetForm = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (svq *SeckillVoucherQuery) loadGetForm(ctx context.Context, query *VoucherQuery, nodes []*SeckillVoucher, init func(*SeckillVoucher), assign func(*SeckillVoucher, *Voucher)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*SeckillVoucher)
	for i := range nodes {
		fk := nodes[i].VoucherID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(voucher.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "voucher_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (svq *SeckillVoucherQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := svq.querySpec()
	_spec.Node.Columns = svq.ctx.Fields
	if len(svq.ctx.Fields) > 0 {
		_spec.Unique = svq.ctx.Unique != nil && *svq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, svq.driver, _spec)
}

func (svq *SeckillVoucherQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(seckillvoucher.Table, seckillvoucher.Columns, sqlgraph.NewFieldSpec(seckillvoucher.FieldID, field.TypeUint64))
	_spec.From = svq.sql
	if unique := svq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if svq.path != nil {
		_spec.Unique = true
	}
	if fields := svq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, seckillvoucher.FieldID)
		for i := range fields {
			if fields[i] != seckillvoucher.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if svq.withGetForm != nil {
			_spec.Node.AddColumnOnce(seckillvoucher.FieldVoucherID)
		}
	}
	if ps := svq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := svq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := svq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := svq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (svq *SeckillVoucherQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(svq.driver.Dialect())
	t1 := builder.Table(seckillvoucher.Table)
	columns := svq.ctx.Fields
	if len(columns) == 0 {
		columns = seckillvoucher.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if svq.sql != nil {
		selector = svq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if svq.ctx.Unique != nil && *svq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range svq.predicates {
		p(selector)
	}
	for _, p := range svq.order {
		p(selector)
	}
	if offset := svq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := svq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SeckillVoucherGroupBy is the group-by builder for SeckillVoucher entities.
type SeckillVoucherGroupBy struct {
	selector
	build *SeckillVoucherQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (svgb *SeckillVoucherGroupBy) Aggregate(fns ...AggregateFunc) *SeckillVoucherGroupBy {
	svgb.fns = append(svgb.fns, fns...)
	return svgb
}

// Scan applies the selector query and scans the result into the given value.
func (svgb *SeckillVoucherGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, svgb.build.ctx, "GroupBy")
	if err := svgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SeckillVoucherQuery, *SeckillVoucherGroupBy](ctx, svgb.build, svgb, svgb.build.inters, v)
}

func (svgb *SeckillVoucherGroupBy) sqlScan(ctx context.Context, root *SeckillVoucherQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(svgb.fns))
	for _, fn := range svgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*svgb.flds)+len(svgb.fns))
		for _, f := range *svgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*svgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := svgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SeckillVoucherSelect is the builder for selecting fields of SeckillVoucher entities.
type SeckillVoucherSelect struct {
	*SeckillVoucherQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (svs *SeckillVoucherSelect) Aggregate(fns ...AggregateFunc) *SeckillVoucherSelect {
	svs.fns = append(svs.fns, fns...)
	return svs
}

// Scan applies the selector query and scans the result into the given value.
func (svs *SeckillVoucherSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, svs.ctx, "Select")
	if err := svs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SeckillVoucherQuery, *SeckillVoucherSelect](ctx, svs.SeckillVoucherQuery, svs, svs.inters, v)
}

func (svs *SeckillVoucherSelect) sqlScan(ctx context.Context, root *SeckillVoucherQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(svs.fns))
	for _, fn := range svs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*svs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := svs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
