// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"hmdp/ent/predicate"
	"hmdp/ent/shoptype"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShopTypeQuery is the builder for querying ShopType entities.
type ShopTypeQuery struct {
	config
	ctx        *QueryContext
	order      []shoptype.OrderOption
	inters     []Interceptor
	predicates []predicate.ShopType
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ShopTypeQuery builder.
func (stq *ShopTypeQuery) Where(ps ...predicate.ShopType) *ShopTypeQuery {
	stq.predicates = append(stq.predicates, ps...)
	return stq
}

// Limit the number of records to be returned by this query.
func (stq *ShopTypeQuery) Limit(limit int) *ShopTypeQuery {
	stq.ctx.Limit = &limit
	return stq
}

// Offset to start from.
func (stq *ShopTypeQuery) Offset(offset int) *ShopTypeQuery {
	stq.ctx.Offset = &offset
	return stq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (stq *ShopTypeQuery) Unique(unique bool) *ShopTypeQuery {
	stq.ctx.Unique = &unique
	return stq
}

// Order specifies how the records should be ordered.
func (stq *ShopTypeQuery) Order(o ...shoptype.OrderOption) *ShopTypeQuery {
	stq.order = append(stq.order, o...)
	return stq
}

// First returns the first ShopType entity from the query.
// Returns a *NotFoundError when no ShopType was found.
func (stq *ShopTypeQuery) First(ctx context.Context) (*ShopType, error) {
	nodes, err := stq.Limit(1).All(setContextOp(ctx, stq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{shoptype.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (stq *ShopTypeQuery) FirstX(ctx context.Context) *ShopType {
	node, err := stq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ShopType ID from the query.
// Returns a *NotFoundError when no ShopType ID was found.
func (stq *ShopTypeQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = stq.Limit(1).IDs(setContextOp(ctx, stq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{shoptype.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (stq *ShopTypeQuery) FirstIDX(ctx context.Context) int64 {
	id, err := stq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ShopType entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ShopType entity is found.
// Returns a *NotFoundError when no ShopType entities are found.
func (stq *ShopTypeQuery) Only(ctx context.Context) (*ShopType, error) {
	nodes, err := stq.Limit(2).All(setContextOp(ctx, stq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{shoptype.Label}
	default:
		return nil, &NotSingularError{shoptype.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (stq *ShopTypeQuery) OnlyX(ctx context.Context) *ShopType {
	node, err := stq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ShopType ID in the query.
// Returns a *NotSingularError when more than one ShopType ID is found.
// Returns a *NotFoundError when no entities are found.
func (stq *ShopTypeQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = stq.Limit(2).IDs(setContextOp(ctx, stq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{shoptype.Label}
	default:
		err = &NotSingularError{shoptype.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (stq *ShopTypeQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := stq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ShopTypes.
func (stq *ShopTypeQuery) All(ctx context.Context) ([]*ShopType, error) {
	ctx = setContextOp(ctx, stq.ctx, "All")
	if err := stq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ShopType, *ShopTypeQuery]()
	return withInterceptors[[]*ShopType](ctx, stq, qr, stq.inters)
}

// AllX is like All, but panics if an error occurs.
func (stq *ShopTypeQuery) AllX(ctx context.Context) []*ShopType {
	nodes, err := stq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ShopType IDs.
func (stq *ShopTypeQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if stq.ctx.Unique == nil && stq.path != nil {
		stq.Unique(true)
	}
	ctx = setContextOp(ctx, stq.ctx, "IDs")
	if err = stq.Select(shoptype.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (stq *ShopTypeQuery) IDsX(ctx context.Context) []int64 {
	ids, err := stq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (stq *ShopTypeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, stq.ctx, "Count")
	if err := stq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, stq, querierCount[*ShopTypeQuery](), stq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (stq *ShopTypeQuery) CountX(ctx context.Context) int {
	count, err := stq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (stq *ShopTypeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, stq.ctx, "Exist")
	switch _, err := stq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (stq *ShopTypeQuery) ExistX(ctx context.Context) bool {
	exist, err := stq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ShopTypeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (stq *ShopTypeQuery) Clone() *ShopTypeQuery {
	if stq == nil {
		return nil
	}
	return &ShopTypeQuery{
		config:     stq.config,
		ctx:        stq.ctx.Clone(),
		order:      append([]shoptype.OrderOption{}, stq.order...),
		inters:     append([]Interceptor{}, stq.inters...),
		predicates: append([]predicate.ShopType{}, stq.predicates...),
		// clone intermediate query.
		sql:  stq.sql.Clone(),
		path: stq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ShopType.Query().
//		GroupBy(shoptype.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (stq *ShopTypeQuery) GroupBy(field string, fields ...string) *ShopTypeGroupBy {
	stq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ShopTypeGroupBy{build: stq}
	grbuild.flds = &stq.ctx.Fields
	grbuild.label = shoptype.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.ShopType.Query().
//		Select(shoptype.FieldName).
//		Scan(ctx, &v)
func (stq *ShopTypeQuery) Select(fields ...string) *ShopTypeSelect {
	stq.ctx.Fields = append(stq.ctx.Fields, fields...)
	sbuild := &ShopTypeSelect{ShopTypeQuery: stq}
	sbuild.label = shoptype.Label
	sbuild.flds, sbuild.scan = &stq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ShopTypeSelect configured with the given aggregations.
func (stq *ShopTypeQuery) Aggregate(fns ...AggregateFunc) *ShopTypeSelect {
	return stq.Select().Aggregate(fns...)
}

func (stq *ShopTypeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range stq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, stq); err != nil {
				return err
			}
		}
	}
	for _, f := range stq.ctx.Fields {
		if !shoptype.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if stq.path != nil {
		prev, err := stq.path(ctx)
		if err != nil {
			return err
		}
		stq.sql = prev
	}
	return nil
}

func (stq *ShopTypeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ShopType, error) {
	var (
		nodes = []*ShopType{}
		_spec = stq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ShopType).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ShopType{config: stq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, stq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (stq *ShopTypeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := stq.querySpec()
	_spec.Node.Columns = stq.ctx.Fields
	if len(stq.ctx.Fields) > 0 {
		_spec.Unique = stq.ctx.Unique != nil && *stq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, stq.driver, _spec)
}

func (stq *ShopTypeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(shoptype.Table, shoptype.Columns, sqlgraph.NewFieldSpec(shoptype.FieldID, field.TypeInt64))
	_spec.From = stq.sql
	if unique := stq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if stq.path != nil {
		_spec.Unique = true
	}
	if fields := stq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, shoptype.FieldID)
		for i := range fields {
			if fields[i] != shoptype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := stq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := stq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := stq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := stq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (stq *ShopTypeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(stq.driver.Dialect())
	t1 := builder.Table(shoptype.Table)
	columns := stq.ctx.Fields
	if len(columns) == 0 {
		columns = shoptype.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if stq.sql != nil {
		selector = stq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if stq.ctx.Unique != nil && *stq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range stq.predicates {
		p(selector)
	}
	for _, p := range stq.order {
		p(selector)
	}
	if offset := stq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := stq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ShopTypeGroupBy is the group-by builder for ShopType entities.
type ShopTypeGroupBy struct {
	selector
	build *ShopTypeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (stgb *ShopTypeGroupBy) Aggregate(fns ...AggregateFunc) *ShopTypeGroupBy {
	stgb.fns = append(stgb.fns, fns...)
	return stgb
}

// Scan applies the selector query and scans the result into the given value.
func (stgb *ShopTypeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, stgb.build.ctx, "GroupBy")
	if err := stgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ShopTypeQuery, *ShopTypeGroupBy](ctx, stgb.build, stgb, stgb.build.inters, v)
}

func (stgb *ShopTypeGroupBy) sqlScan(ctx context.Context, root *ShopTypeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(stgb.fns))
	for _, fn := range stgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*stgb.flds)+len(stgb.fns))
		for _, f := range *stgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*stgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := stgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ShopTypeSelect is the builder for selecting fields of ShopType entities.
type ShopTypeSelect struct {
	*ShopTypeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sts *ShopTypeSelect) Aggregate(fns ...AggregateFunc) *ShopTypeSelect {
	sts.fns = append(sts.fns, fns...)
	return sts
}

// Scan applies the selector query and scans the result into the given value.
func (sts *ShopTypeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sts.ctx, "Select")
	if err := sts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ShopTypeQuery, *ShopTypeSelect](ctx, sts.ShopTypeQuery, sts, sts.inters, v)
}

func (sts *ShopTypeSelect) sqlScan(ctx context.Context, root *ShopTypeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sts.fns))
	for _, fn := range sts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
