// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"hmdp/ent/predicate"
	"hmdp/ent/voucherorder"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// VoucherOrderDelete is the builder for deleting a VoucherOrder entity.
type VoucherOrderDelete struct {
	config
	hooks    []Hook
	mutation *VoucherOrderMutation
}

// Where appends a list predicates to the VoucherOrderDelete builder.
func (vod *VoucherOrderDelete) Where(ps ...predicate.VoucherOrder) *VoucherOrderDelete {
	vod.mutation.Where(ps...)
	return vod
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (vod *VoucherOrderDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, vod.sqlExec, vod.mutation, vod.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (vod *VoucherOrderDelete) ExecX(ctx context.Context) int {
	n, err := vod.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (vod *VoucherOrderDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(voucherorder.Table, sqlgraph.NewFieldSpec(voucherorder.FieldID, field.TypeInt64))
	if ps := vod.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, vod.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	vod.mutation.done = true
	return affected, err
}

// VoucherOrderDeleteOne is the builder for deleting a single VoucherOrder entity.
type VoucherOrderDeleteOne struct {
	vod *VoucherOrderDelete
}

// Where appends a list predicates to the VoucherOrderDelete builder.
func (vodo *VoucherOrderDeleteOne) Where(ps ...predicate.VoucherOrder) *VoucherOrderDeleteOne {
	vodo.vod.mutation.Where(ps...)
	return vodo
}

// Exec executes the deletion query.
func (vodo *VoucherOrderDeleteOne) Exec(ctx context.Context) error {
	n, err := vodo.vod.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{voucherorder.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (vodo *VoucherOrderDeleteOne) ExecX(ctx context.Context) {
	if err := vodo.Exec(ctx); err != nil {
		panic(err)
	}
}
