// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Blog is the predicate function for blog builders.
type Blog func(*sql.Selector)

// SeckillVoucher is the predicate function for seckillvoucher builders.
type SeckillVoucher func(*sql.Selector)

// Shop is the predicate function for shop builders.
type Shop func(*sql.Selector)

// ShopType is the predicate function for shoptype builders.
type ShopType func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Voucher is the predicate function for voucher builders.
type Voucher func(*sql.Selector)

// VoucherOrder is the predicate function for voucherorder builders.
type VoucherOrder func(*sql.Selector)
